using System;
using System.Numerics;
using System.Reflection;

//Guessing a number generated by computer
//int numberToGuess = new Random().Next(1, 101);
//int UserGuess = 0, tries = 0, MaxGuess = 7;
//bool winner = false;


/*while (UserGuess != numberToGuess) {
    if(tries > MaxGuess - 1) {
        Console.WriteLine ("You have reached the max number to guesses:" + MaxGuess);
        break;
    }

    tries++;
    Console.WriteLine ("Enter the guess:");
    bool result = int.TryParse (Console.ReadLine (), out UserGuess);
    if (result && (UserGuess >= 1 && UserGuess <= 100)) {
        if (UserGuess < numberToGuess) Console.WriteLine ($"{UserGuess} is Lower");
        else if (UserGuess > numberToGuess) Console.WriteLine ($"{UserGuess} is higher");
        else Console.WriteLine ($"{UserGuess} is a correct guess after {tries} tries");
    } else Console.WriteLine ("Invalid input. Please provide a number between 1 and 100");
}*/

//Guessing a number thought by user

int lowerLimit = 1, upperLimit = 128;
var tries=0;
Random random = new ();
setRange (lowerLimit, upperLimit);
    

void setRange (int minValue, int maxValue) {
    bool isExact = false;
    //int guess = new Random ().Next (minValue,maxValue);
    int guess = midValue (minValue, maxValue);

    while (!isExact) {
        tries++;
     
            switch (GetResponse (guess)) {
                case "1": isExact = true; break;
                case "2": maxValue = guess; guess = midValue (minValue, guess); break;
                case "3": minValue = guess; guess = midValue (guess, maxValue); break;
                default: Console.WriteLine ("Invalid input. Please provide a number between 1 and 127"); break;
            }

        }
    Console.WriteLine ($"{guess} is correct with {tries} tries!");
}



//int midValue (int minValue, int maxValue) => minValue + ((maxValue - minValue) / 2);
int midValue(int minValue, int maxValue) => random.Next (minValue + 1, maxValue - 1);

string GetResponse (int guess) {    
    Console.WriteLine ("Type number 1 (exact) or 2 (low) or 3 (high): ");
    Console.WriteLine ($"Is the number {guess} or lesser than {guess} or higher than {guess}?");
    string response = Console.ReadLine ();
    return response;
}
