using System;
using System.Numerics;
using System.Reflection;

//Guessing a number generated by computer
//int numberToGuess = new Random().Next(1, 101);
//int UserGuess = 0, tries = 0, MaxGuess = 7;
//bool winner = false;


/*while (UserGuess != numberToGuess) {
    if(tries > MaxGuess - 1) {
        Console.WriteLine ("You have reached the max number to guesses:" + MaxGuess);
        break;
    }

    tries++;
    Console.WriteLine ("Enter the guess:");
    bool result = int.TryParse (Console.ReadLine (), out UserGuess);
    if (result && (UserGuess >= 1 && UserGuess <= 100)) {
        if (UserGuess < numberToGuess) Console.WriteLine ($"{UserGuess} is Lower");
        else if (UserGuess > numberToGuess) Console.WriteLine ($"{UserGuess} is higher");
        else Console.WriteLine ($"{UserGuess} is a correct guess after {tries} tries");
    } else Console.WriteLine ("Invalid input. Please provide a number between 1 and 100");
}*/

//Guessing a number thought by user

int lowerLimit = 1, upperLimit = 128;
var tries=0;
Console.WriteLine ("Type exact or low or high: ");
setRange (lowerLimit, upperLimit);
    

void setRange (int minValue, int maxValue) {
     bool isExact = false;
     int guess = midValue (minValue, maxValue);

        while (!isExact) {
        tries++;
     
            switch (GetResponse (guess)) {
                //GetResponse (guess).ToUpper;
                case "exact": isExact = true; break;
                case "low": maxValue = guess; guess = midValue (minValue, guess); break;
                case "high": minValue = guess; guess = midValue (guess, maxValue); break;
                default: Console.WriteLine ("Invalid input. Please provide a number between 1 and 127"); break;
            }

        }
    Console.WriteLine ($"{guess} is correct with {tries} tries!");
}
int midValue (int minValue, int maxValue) => minValue + ((maxValue - minValue) / 2);

string GetResponse (int guess) {    
     Console.WriteLine ($"Is the number {guess} or lesser than {guess} or higher than {guess}?");
    return Console.ReadLine ();

}
